"""Add streak tracking to User model

Revision ID: a575a97c492f
Revises: 41d91b9a0b6e
Create Date: 2025-10-10 11:37:57.901680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a575a97c492f'
down_revision = '41d91b9a0b6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_streak', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('longest_streak', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('streak_start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_entry_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_entry_date')
        batch_op.drop_column('streak_start_date')
        batch_op.drop_column('longest_streak')
        batch_op.drop_column('current_streak')

    # ### end Alembic commands ###
